name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Node.js (Optional, if your site doesn't use Node, skip this)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Your site is in the root of the repo
